
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ParentalTip` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ParentalTip
 * 
 */
export type ParentalTipModel = runtime.Types.Result.DefaultSelection<Prisma.$ParentalTipPayload>

export type AggregateParentalTip = {
  _count: ParentalTipCountAggregateOutputType | null
  _min: ParentalTipMinAggregateOutputType | null
  _max: ParentalTipMaxAggregateOutputType | null
}

export type ParentalTipMinAggregateOutputType = {
  id: string | null
  title: string | null
  content: string | null
  created_at: Date | null
}

export type ParentalTipMaxAggregateOutputType = {
  id: string | null
  title: string | null
  content: string | null
  created_at: Date | null
}

export type ParentalTipCountAggregateOutputType = {
  id: number
  title: number
  content: number
  created_at: number
  _all: number
}


export type ParentalTipMinAggregateInputType = {
  id?: true
  title?: true
  content?: true
  created_at?: true
}

export type ParentalTipMaxAggregateInputType = {
  id?: true
  title?: true
  content?: true
  created_at?: true
}

export type ParentalTipCountAggregateInputType = {
  id?: true
  title?: true
  content?: true
  created_at?: true
  _all?: true
}

export type ParentalTipAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ParentalTip to aggregate.
   */
  where?: Prisma.ParentalTipWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ParentalTips to fetch.
   */
  orderBy?: Prisma.ParentalTipOrderByWithRelationInput | Prisma.ParentalTipOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ParentalTipWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ParentalTips from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ParentalTips.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ParentalTips
  **/
  _count?: true | ParentalTipCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ParentalTipMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ParentalTipMaxAggregateInputType
}

export type GetParentalTipAggregateType<T extends ParentalTipAggregateArgs> = {
      [P in keyof T & keyof AggregateParentalTip]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateParentalTip[P]>
    : Prisma.GetScalarType<T[P], AggregateParentalTip[P]>
}




export type ParentalTipGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ParentalTipWhereInput
  orderBy?: Prisma.ParentalTipOrderByWithAggregationInput | Prisma.ParentalTipOrderByWithAggregationInput[]
  by: Prisma.ParentalTipScalarFieldEnum[] | Prisma.ParentalTipScalarFieldEnum
  having?: Prisma.ParentalTipScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ParentalTipCountAggregateInputType | true
  _min?: ParentalTipMinAggregateInputType
  _max?: ParentalTipMaxAggregateInputType
}

export type ParentalTipGroupByOutputType = {
  id: string
  title: string
  content: string
  created_at: Date
  _count: ParentalTipCountAggregateOutputType | null
  _min: ParentalTipMinAggregateOutputType | null
  _max: ParentalTipMaxAggregateOutputType | null
}

export type GetParentalTipGroupByPayload<T extends ParentalTipGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ParentalTipGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ParentalTipGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ParentalTipGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ParentalTipGroupByOutputType[P]>
      }
    >
  >



export type ParentalTipWhereInput = {
  AND?: Prisma.ParentalTipWhereInput | Prisma.ParentalTipWhereInput[]
  OR?: Prisma.ParentalTipWhereInput[]
  NOT?: Prisma.ParentalTipWhereInput | Prisma.ParentalTipWhereInput[]
  id?: Prisma.StringFilter<"ParentalTip"> | string
  title?: Prisma.StringFilter<"ParentalTip"> | string
  content?: Prisma.StringFilter<"ParentalTip"> | string
  created_at?: Prisma.DateTimeFilter<"ParentalTip"> | Date | string
}

export type ParentalTipOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type ParentalTipWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ParentalTipWhereInput | Prisma.ParentalTipWhereInput[]
  OR?: Prisma.ParentalTipWhereInput[]
  NOT?: Prisma.ParentalTipWhereInput | Prisma.ParentalTipWhereInput[]
  title?: Prisma.StringFilter<"ParentalTip"> | string
  content?: Prisma.StringFilter<"ParentalTip"> | string
  created_at?: Prisma.DateTimeFilter<"ParentalTip"> | Date | string
}, "id">

export type ParentalTipOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.ParentalTipCountOrderByAggregateInput
  _max?: Prisma.ParentalTipMaxOrderByAggregateInput
  _min?: Prisma.ParentalTipMinOrderByAggregateInput
}

export type ParentalTipScalarWhereWithAggregatesInput = {
  AND?: Prisma.ParentalTipScalarWhereWithAggregatesInput | Prisma.ParentalTipScalarWhereWithAggregatesInput[]
  OR?: Prisma.ParentalTipScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ParentalTipScalarWhereWithAggregatesInput | Prisma.ParentalTipScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ParentalTip"> | string
  title?: Prisma.StringWithAggregatesFilter<"ParentalTip"> | string
  content?: Prisma.StringWithAggregatesFilter<"ParentalTip"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"ParentalTip"> | Date | string
}

export type ParentalTipCreateInput = {
  id?: string
  title: string
  content: string
  created_at?: Date | string
}

export type ParentalTipUncheckedCreateInput = {
  id?: string
  title: string
  content: string
  created_at?: Date | string
}

export type ParentalTipUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ParentalTipUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ParentalTipCreateManyInput = {
  id?: string
  title: string
  content: string
  created_at?: Date | string
}

export type ParentalTipUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ParentalTipUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ParentalTipCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type ParentalTipMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type ParentalTipMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}



export type ParentalTipSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  created_at?: boolean
}, ExtArgs["result"]["parentalTip"]>

export type ParentalTipSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  created_at?: boolean
}, ExtArgs["result"]["parentalTip"]>

export type ParentalTipSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  created_at?: boolean
}, ExtArgs["result"]["parentalTip"]>

export type ParentalTipSelectScalar = {
  id?: boolean
  title?: boolean
  content?: boolean
  created_at?: boolean
}

export type ParentalTipOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "content" | "created_at", ExtArgs["result"]["parentalTip"]>

export type $ParentalTipPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ParentalTip"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    content: string
    created_at: Date
  }, ExtArgs["result"]["parentalTip"]>
  composites: {}
}

export type ParentalTipGetPayload<S extends boolean | null | undefined | ParentalTipDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ParentalTipPayload, S>

export type ParentalTipCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ParentalTipFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ParentalTipCountAggregateInputType | true
  }

export interface ParentalTipDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ParentalTip'], meta: { name: 'ParentalTip' } }
  /**
   * Find zero or one ParentalTip that matches the filter.
   * @param {ParentalTipFindUniqueArgs} args - Arguments to find a ParentalTip
   * @example
   * // Get one ParentalTip
   * const parentalTip = await prisma.parentalTip.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ParentalTipFindUniqueArgs>(args: Prisma.SelectSubset<T, ParentalTipFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ParentalTipClient<runtime.Types.Result.GetResult<Prisma.$ParentalTipPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ParentalTip that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ParentalTipFindUniqueOrThrowArgs} args - Arguments to find a ParentalTip
   * @example
   * // Get one ParentalTip
   * const parentalTip = await prisma.parentalTip.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ParentalTipFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ParentalTipFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ParentalTipClient<runtime.Types.Result.GetResult<Prisma.$ParentalTipPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ParentalTip that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParentalTipFindFirstArgs} args - Arguments to find a ParentalTip
   * @example
   * // Get one ParentalTip
   * const parentalTip = await prisma.parentalTip.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ParentalTipFindFirstArgs>(args?: Prisma.SelectSubset<T, ParentalTipFindFirstArgs<ExtArgs>>): Prisma.Prisma__ParentalTipClient<runtime.Types.Result.GetResult<Prisma.$ParentalTipPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ParentalTip that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParentalTipFindFirstOrThrowArgs} args - Arguments to find a ParentalTip
   * @example
   * // Get one ParentalTip
   * const parentalTip = await prisma.parentalTip.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ParentalTipFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ParentalTipFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ParentalTipClient<runtime.Types.Result.GetResult<Prisma.$ParentalTipPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ParentalTips that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParentalTipFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ParentalTips
   * const parentalTips = await prisma.parentalTip.findMany()
   * 
   * // Get first 10 ParentalTips
   * const parentalTips = await prisma.parentalTip.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const parentalTipWithIdOnly = await prisma.parentalTip.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ParentalTipFindManyArgs>(args?: Prisma.SelectSubset<T, ParentalTipFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ParentalTipPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ParentalTip.
   * @param {ParentalTipCreateArgs} args - Arguments to create a ParentalTip.
   * @example
   * // Create one ParentalTip
   * const ParentalTip = await prisma.parentalTip.create({
   *   data: {
   *     // ... data to create a ParentalTip
   *   }
   * })
   * 
   */
  create<T extends ParentalTipCreateArgs>(args: Prisma.SelectSubset<T, ParentalTipCreateArgs<ExtArgs>>): Prisma.Prisma__ParentalTipClient<runtime.Types.Result.GetResult<Prisma.$ParentalTipPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ParentalTips.
   * @param {ParentalTipCreateManyArgs} args - Arguments to create many ParentalTips.
   * @example
   * // Create many ParentalTips
   * const parentalTip = await prisma.parentalTip.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ParentalTipCreateManyArgs>(args?: Prisma.SelectSubset<T, ParentalTipCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ParentalTips and returns the data saved in the database.
   * @param {ParentalTipCreateManyAndReturnArgs} args - Arguments to create many ParentalTips.
   * @example
   * // Create many ParentalTips
   * const parentalTip = await prisma.parentalTip.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ParentalTips and only return the `id`
   * const parentalTipWithIdOnly = await prisma.parentalTip.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ParentalTipCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ParentalTipCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ParentalTipPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ParentalTip.
   * @param {ParentalTipDeleteArgs} args - Arguments to delete one ParentalTip.
   * @example
   * // Delete one ParentalTip
   * const ParentalTip = await prisma.parentalTip.delete({
   *   where: {
   *     // ... filter to delete one ParentalTip
   *   }
   * })
   * 
   */
  delete<T extends ParentalTipDeleteArgs>(args: Prisma.SelectSubset<T, ParentalTipDeleteArgs<ExtArgs>>): Prisma.Prisma__ParentalTipClient<runtime.Types.Result.GetResult<Prisma.$ParentalTipPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ParentalTip.
   * @param {ParentalTipUpdateArgs} args - Arguments to update one ParentalTip.
   * @example
   * // Update one ParentalTip
   * const parentalTip = await prisma.parentalTip.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ParentalTipUpdateArgs>(args: Prisma.SelectSubset<T, ParentalTipUpdateArgs<ExtArgs>>): Prisma.Prisma__ParentalTipClient<runtime.Types.Result.GetResult<Prisma.$ParentalTipPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ParentalTips.
   * @param {ParentalTipDeleteManyArgs} args - Arguments to filter ParentalTips to delete.
   * @example
   * // Delete a few ParentalTips
   * const { count } = await prisma.parentalTip.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ParentalTipDeleteManyArgs>(args?: Prisma.SelectSubset<T, ParentalTipDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ParentalTips.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParentalTipUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ParentalTips
   * const parentalTip = await prisma.parentalTip.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ParentalTipUpdateManyArgs>(args: Prisma.SelectSubset<T, ParentalTipUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ParentalTips and returns the data updated in the database.
   * @param {ParentalTipUpdateManyAndReturnArgs} args - Arguments to update many ParentalTips.
   * @example
   * // Update many ParentalTips
   * const parentalTip = await prisma.parentalTip.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ParentalTips and only return the `id`
   * const parentalTipWithIdOnly = await prisma.parentalTip.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ParentalTipUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ParentalTipUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ParentalTipPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ParentalTip.
   * @param {ParentalTipUpsertArgs} args - Arguments to update or create a ParentalTip.
   * @example
   * // Update or create a ParentalTip
   * const parentalTip = await prisma.parentalTip.upsert({
   *   create: {
   *     // ... data to create a ParentalTip
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ParentalTip we want to update
   *   }
   * })
   */
  upsert<T extends ParentalTipUpsertArgs>(args: Prisma.SelectSubset<T, ParentalTipUpsertArgs<ExtArgs>>): Prisma.Prisma__ParentalTipClient<runtime.Types.Result.GetResult<Prisma.$ParentalTipPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ParentalTips.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParentalTipCountArgs} args - Arguments to filter ParentalTips to count.
   * @example
   * // Count the number of ParentalTips
   * const count = await prisma.parentalTip.count({
   *   where: {
   *     // ... the filter for the ParentalTips we want to count
   *   }
   * })
  **/
  count<T extends ParentalTipCountArgs>(
    args?: Prisma.Subset<T, ParentalTipCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ParentalTipCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ParentalTip.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParentalTipAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ParentalTipAggregateArgs>(args: Prisma.Subset<T, ParentalTipAggregateArgs>): Prisma.PrismaPromise<GetParentalTipAggregateType<T>>

  /**
   * Group by ParentalTip.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParentalTipGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ParentalTipGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ParentalTipGroupByArgs['orderBy'] }
      : { orderBy?: ParentalTipGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ParentalTipGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetParentalTipGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ParentalTip model
 */
readonly fields: ParentalTipFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ParentalTip.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ParentalTipClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ParentalTip model
 */
export interface ParentalTipFieldRefs {
  readonly id: Prisma.FieldRef<"ParentalTip", 'String'>
  readonly title: Prisma.FieldRef<"ParentalTip", 'String'>
  readonly content: Prisma.FieldRef<"ParentalTip", 'String'>
  readonly created_at: Prisma.FieldRef<"ParentalTip", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ParentalTip findUnique
 */
export type ParentalTipFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParentalTip
   */
  select?: Prisma.ParentalTipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParentalTip
   */
  omit?: Prisma.ParentalTipOmit<ExtArgs> | null
  /**
   * Filter, which ParentalTip to fetch.
   */
  where: Prisma.ParentalTipWhereUniqueInput
}

/**
 * ParentalTip findUniqueOrThrow
 */
export type ParentalTipFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParentalTip
   */
  select?: Prisma.ParentalTipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParentalTip
   */
  omit?: Prisma.ParentalTipOmit<ExtArgs> | null
  /**
   * Filter, which ParentalTip to fetch.
   */
  where: Prisma.ParentalTipWhereUniqueInput
}

/**
 * ParentalTip findFirst
 */
export type ParentalTipFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParentalTip
   */
  select?: Prisma.ParentalTipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParentalTip
   */
  omit?: Prisma.ParentalTipOmit<ExtArgs> | null
  /**
   * Filter, which ParentalTip to fetch.
   */
  where?: Prisma.ParentalTipWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ParentalTips to fetch.
   */
  orderBy?: Prisma.ParentalTipOrderByWithRelationInput | Prisma.ParentalTipOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ParentalTips.
   */
  cursor?: Prisma.ParentalTipWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ParentalTips from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ParentalTips.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ParentalTips.
   */
  distinct?: Prisma.ParentalTipScalarFieldEnum | Prisma.ParentalTipScalarFieldEnum[]
}

/**
 * ParentalTip findFirstOrThrow
 */
export type ParentalTipFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParentalTip
   */
  select?: Prisma.ParentalTipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParentalTip
   */
  omit?: Prisma.ParentalTipOmit<ExtArgs> | null
  /**
   * Filter, which ParentalTip to fetch.
   */
  where?: Prisma.ParentalTipWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ParentalTips to fetch.
   */
  orderBy?: Prisma.ParentalTipOrderByWithRelationInput | Prisma.ParentalTipOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ParentalTips.
   */
  cursor?: Prisma.ParentalTipWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ParentalTips from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ParentalTips.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ParentalTips.
   */
  distinct?: Prisma.ParentalTipScalarFieldEnum | Prisma.ParentalTipScalarFieldEnum[]
}

/**
 * ParentalTip findMany
 */
export type ParentalTipFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParentalTip
   */
  select?: Prisma.ParentalTipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParentalTip
   */
  omit?: Prisma.ParentalTipOmit<ExtArgs> | null
  /**
   * Filter, which ParentalTips to fetch.
   */
  where?: Prisma.ParentalTipWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ParentalTips to fetch.
   */
  orderBy?: Prisma.ParentalTipOrderByWithRelationInput | Prisma.ParentalTipOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ParentalTips.
   */
  cursor?: Prisma.ParentalTipWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ParentalTips from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ParentalTips.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ParentalTips.
   */
  distinct?: Prisma.ParentalTipScalarFieldEnum | Prisma.ParentalTipScalarFieldEnum[]
}

/**
 * ParentalTip create
 */
export type ParentalTipCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParentalTip
   */
  select?: Prisma.ParentalTipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParentalTip
   */
  omit?: Prisma.ParentalTipOmit<ExtArgs> | null
  /**
   * The data needed to create a ParentalTip.
   */
  data: Prisma.XOR<Prisma.ParentalTipCreateInput, Prisma.ParentalTipUncheckedCreateInput>
}

/**
 * ParentalTip createMany
 */
export type ParentalTipCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ParentalTips.
   */
  data: Prisma.ParentalTipCreateManyInput | Prisma.ParentalTipCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ParentalTip createManyAndReturn
 */
export type ParentalTipCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParentalTip
   */
  select?: Prisma.ParentalTipSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ParentalTip
   */
  omit?: Prisma.ParentalTipOmit<ExtArgs> | null
  /**
   * The data used to create many ParentalTips.
   */
  data: Prisma.ParentalTipCreateManyInput | Prisma.ParentalTipCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ParentalTip update
 */
export type ParentalTipUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParentalTip
   */
  select?: Prisma.ParentalTipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParentalTip
   */
  omit?: Prisma.ParentalTipOmit<ExtArgs> | null
  /**
   * The data needed to update a ParentalTip.
   */
  data: Prisma.XOR<Prisma.ParentalTipUpdateInput, Prisma.ParentalTipUncheckedUpdateInput>
  /**
   * Choose, which ParentalTip to update.
   */
  where: Prisma.ParentalTipWhereUniqueInput
}

/**
 * ParentalTip updateMany
 */
export type ParentalTipUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ParentalTips.
   */
  data: Prisma.XOR<Prisma.ParentalTipUpdateManyMutationInput, Prisma.ParentalTipUncheckedUpdateManyInput>
  /**
   * Filter which ParentalTips to update
   */
  where?: Prisma.ParentalTipWhereInput
  /**
   * Limit how many ParentalTips to update.
   */
  limit?: number
}

/**
 * ParentalTip updateManyAndReturn
 */
export type ParentalTipUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParentalTip
   */
  select?: Prisma.ParentalTipSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ParentalTip
   */
  omit?: Prisma.ParentalTipOmit<ExtArgs> | null
  /**
   * The data used to update ParentalTips.
   */
  data: Prisma.XOR<Prisma.ParentalTipUpdateManyMutationInput, Prisma.ParentalTipUncheckedUpdateManyInput>
  /**
   * Filter which ParentalTips to update
   */
  where?: Prisma.ParentalTipWhereInput
  /**
   * Limit how many ParentalTips to update.
   */
  limit?: number
}

/**
 * ParentalTip upsert
 */
export type ParentalTipUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParentalTip
   */
  select?: Prisma.ParentalTipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParentalTip
   */
  omit?: Prisma.ParentalTipOmit<ExtArgs> | null
  /**
   * The filter to search for the ParentalTip to update in case it exists.
   */
  where: Prisma.ParentalTipWhereUniqueInput
  /**
   * In case the ParentalTip found by the `where` argument doesn't exist, create a new ParentalTip with this data.
   */
  create: Prisma.XOR<Prisma.ParentalTipCreateInput, Prisma.ParentalTipUncheckedCreateInput>
  /**
   * In case the ParentalTip was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ParentalTipUpdateInput, Prisma.ParentalTipUncheckedUpdateInput>
}

/**
 * ParentalTip delete
 */
export type ParentalTipDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParentalTip
   */
  select?: Prisma.ParentalTipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParentalTip
   */
  omit?: Prisma.ParentalTipOmit<ExtArgs> | null
  /**
   * Filter which ParentalTip to delete.
   */
  where: Prisma.ParentalTipWhereUniqueInput
}

/**
 * ParentalTip deleteMany
 */
export type ParentalTipDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ParentalTips to delete
   */
  where?: Prisma.ParentalTipWhereInput
  /**
   * Limit how many ParentalTips to delete.
   */
  limit?: number
}

/**
 * ParentalTip without action
 */
export type ParentalTipDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParentalTip
   */
  select?: Prisma.ParentalTipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParentalTip
   */
  omit?: Prisma.ParentalTipOmit<ExtArgs> | null
}
