
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `User` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model User
 * 
 */
export type UserModel = runtime.Types.Result.DefaultSelection<Prisma.$UserPayload>

export type AggregateUser = {
  _count: UserCountAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

export type UserMinAggregateOutputType = {
  id: string | null
  family_id: string | null
  email: string | null
  password_hash: string | null
  alias: string | null
  role: $Enums.Role | null
  avatar_icon: string | null
  timezone: string | null
}

export type UserMaxAggregateOutputType = {
  id: string | null
  family_id: string | null
  email: string | null
  password_hash: string | null
  alias: string | null
  role: $Enums.Role | null
  avatar_icon: string | null
  timezone: string | null
}

export type UserCountAggregateOutputType = {
  id: number
  family_id: number
  email: number
  password_hash: number
  alias: number
  role: number
  avatar_icon: number
  timezone: number
  _all: number
}


export type UserMinAggregateInputType = {
  id?: true
  family_id?: true
  email?: true
  password_hash?: true
  alias?: true
  role?: true
  avatar_icon?: true
  timezone?: true
}

export type UserMaxAggregateInputType = {
  id?: true
  family_id?: true
  email?: true
  password_hash?: true
  alias?: true
  role?: true
  avatar_icon?: true
  timezone?: true
}

export type UserCountAggregateInputType = {
  id?: true
  family_id?: true
  email?: true
  password_hash?: true
  alias?: true
  role?: true
  avatar_icon?: true
  timezone?: true
  _all?: true
}

export type UserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which User to aggregate.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Users
  **/
  _count?: true | UserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserMaxAggregateInputType
}

export type GetUserAggregateType<T extends UserAggregateArgs> = {
      [P in keyof T & keyof AggregateUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUser[P]>
    : Prisma.GetScalarType<T[P], AggregateUser[P]>
}




export type UserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithAggregationInput | Prisma.UserOrderByWithAggregationInput[]
  by: Prisma.UserScalarFieldEnum[] | Prisma.UserScalarFieldEnum
  having?: Prisma.UserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserCountAggregateInputType | true
  _min?: UserMinAggregateInputType
  _max?: UserMaxAggregateInputType
}

export type UserGroupByOutputType = {
  id: string
  family_id: string
  email: string | null
  password_hash: string
  alias: string
  role: $Enums.Role
  avatar_icon: string
  timezone: string
  _count: UserCountAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

export type GetUserGroupByPayload<T extends UserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
      }
    >
  >



export type UserWhereInput = {
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  id?: Prisma.UuidFilter<"User"> | string
  family_id?: Prisma.UuidFilter<"User"> | string
  email?: Prisma.StringNullableFilter<"User"> | string | null
  password_hash?: Prisma.StringFilter<"User"> | string
  alias?: Prisma.StringFilter<"User"> | string
  role?: Prisma.EnumRoleFilter<"User"> | $Enums.Role
  avatar_icon?: Prisma.StringFilter<"User"> | string
  timezone?: Prisma.StringFilter<"User"> | string
  family?: Prisma.XOR<Prisma.FamilyScalarRelationFilter, Prisma.FamilyWhereInput>
  mood_logs?: Prisma.MoodLogListRelationFilter
  calendar_events?: Prisma.CalendarEventListRelationFilter
  daily_reminders?: Prisma.DailyReminderListRelationFilter
}

export type UserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  family_id?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  alias?: Prisma.SortOrder
  role?: Prisma.SortOrder
  avatar_icon?: Prisma.SortOrder
  timezone?: Prisma.SortOrder
  family?: Prisma.FamilyOrderByWithRelationInput
  mood_logs?: Prisma.MoodLogOrderByRelationAggregateInput
  calendar_events?: Prisma.CalendarEventOrderByRelationAggregateInput
  daily_reminders?: Prisma.DailyReminderOrderByRelationAggregateInput
}

export type UserWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  alias?: string
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  family_id?: Prisma.UuidFilter<"User"> | string
  password_hash?: Prisma.StringFilter<"User"> | string
  role?: Prisma.EnumRoleFilter<"User"> | $Enums.Role
  avatar_icon?: Prisma.StringFilter<"User"> | string
  timezone?: Prisma.StringFilter<"User"> | string
  family?: Prisma.XOR<Prisma.FamilyScalarRelationFilter, Prisma.FamilyWhereInput>
  mood_logs?: Prisma.MoodLogListRelationFilter
  calendar_events?: Prisma.CalendarEventListRelationFilter
  daily_reminders?: Prisma.DailyReminderListRelationFilter
}, "id" | "email" | "alias">

export type UserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  family_id?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  alias?: Prisma.SortOrder
  role?: Prisma.SortOrder
  avatar_icon?: Prisma.SortOrder
  timezone?: Prisma.SortOrder
  _count?: Prisma.UserCountOrderByAggregateInput
  _max?: Prisma.UserMaxOrderByAggregateInput
  _min?: Prisma.UserMinOrderByAggregateInput
}

export type UserScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"User"> | string
  family_id?: Prisma.UuidWithAggregatesFilter<"User"> | string
  email?: Prisma.StringNullableWithAggregatesFilter<"User"> | string | null
  password_hash?: Prisma.StringWithAggregatesFilter<"User"> | string
  alias?: Prisma.StringWithAggregatesFilter<"User"> | string
  role?: Prisma.EnumRoleWithAggregatesFilter<"User"> | $Enums.Role
  avatar_icon?: Prisma.StringWithAggregatesFilter<"User"> | string
  timezone?: Prisma.StringWithAggregatesFilter<"User"> | string
}

export type UserCreateInput = {
  id?: string
  email?: string | null
  password_hash: string
  alias: string
  role?: $Enums.Role
  avatar_icon: string
  timezone?: string
  family: Prisma.FamilyCreateNestedOneWithoutUsersInput
  mood_logs?: Prisma.MoodLogCreateNestedManyWithoutUserInput
  calendar_events?: Prisma.CalendarEventCreateNestedManyWithoutUserInput
  daily_reminders?: Prisma.DailyReminderCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateInput = {
  id?: string
  family_id: string
  email?: string | null
  password_hash: string
  alias: string
  role?: $Enums.Role
  avatar_icon: string
  timezone?: string
  mood_logs?: Prisma.MoodLogUncheckedCreateNestedManyWithoutUserInput
  calendar_events?: Prisma.CalendarEventUncheckedCreateNestedManyWithoutUserInput
  daily_reminders?: Prisma.DailyReminderUncheckedCreateNestedManyWithoutUserInput
}

export type UserUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  alias?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  avatar_icon?: Prisma.StringFieldUpdateOperationsInput | string
  timezone?: Prisma.StringFieldUpdateOperationsInput | string
  family?: Prisma.FamilyUpdateOneRequiredWithoutUsersNestedInput
  mood_logs?: Prisma.MoodLogUpdateManyWithoutUserNestedInput
  calendar_events?: Prisma.CalendarEventUpdateManyWithoutUserNestedInput
  daily_reminders?: Prisma.DailyReminderUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  family_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  alias?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  avatar_icon?: Prisma.StringFieldUpdateOperationsInput | string
  timezone?: Prisma.StringFieldUpdateOperationsInput | string
  mood_logs?: Prisma.MoodLogUncheckedUpdateManyWithoutUserNestedInput
  calendar_events?: Prisma.CalendarEventUncheckedUpdateManyWithoutUserNestedInput
  daily_reminders?: Prisma.DailyReminderUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateManyInput = {
  id?: string
  family_id: string
  email?: string | null
  password_hash: string
  alias: string
  role?: $Enums.Role
  avatar_icon: string
  timezone?: string
}

export type UserUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  alias?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  avatar_icon?: Prisma.StringFieldUpdateOperationsInput | string
  timezone?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  family_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  alias?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  avatar_icon?: Prisma.StringFieldUpdateOperationsInput | string
  timezone?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserListRelationFilter = {
  every?: Prisma.UserWhereInput
  some?: Prisma.UserWhereInput
  none?: Prisma.UserWhereInput
}

export type UserOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  family_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  alias?: Prisma.SortOrder
  role?: Prisma.SortOrder
  avatar_icon?: Prisma.SortOrder
  timezone?: Prisma.SortOrder
}

export type UserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  family_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  alias?: Prisma.SortOrder
  role?: Prisma.SortOrder
  avatar_icon?: Prisma.SortOrder
  timezone?: Prisma.SortOrder
}

export type UserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  family_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  alias?: Prisma.SortOrder
  role?: Prisma.SortOrder
  avatar_icon?: Prisma.SortOrder
  timezone?: Prisma.SortOrder
}

export type UserScalarRelationFilter = {
  is?: Prisma.UserWhereInput
  isNot?: Prisma.UserWhereInput
}

export type UserCreateNestedManyWithoutFamilyInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutFamilyInput, Prisma.UserUncheckedCreateWithoutFamilyInput> | Prisma.UserCreateWithoutFamilyInput[] | Prisma.UserUncheckedCreateWithoutFamilyInput[]
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutFamilyInput | Prisma.UserCreateOrConnectWithoutFamilyInput[]
  createMany?: Prisma.UserCreateManyFamilyInputEnvelope
  connect?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
}

export type UserUncheckedCreateNestedManyWithoutFamilyInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutFamilyInput, Prisma.UserUncheckedCreateWithoutFamilyInput> | Prisma.UserCreateWithoutFamilyInput[] | Prisma.UserUncheckedCreateWithoutFamilyInput[]
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutFamilyInput | Prisma.UserCreateOrConnectWithoutFamilyInput[]
  createMany?: Prisma.UserCreateManyFamilyInputEnvelope
  connect?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
}

export type UserUpdateManyWithoutFamilyNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutFamilyInput, Prisma.UserUncheckedCreateWithoutFamilyInput> | Prisma.UserCreateWithoutFamilyInput[] | Prisma.UserUncheckedCreateWithoutFamilyInput[]
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutFamilyInput | Prisma.UserCreateOrConnectWithoutFamilyInput[]
  upsert?: Prisma.UserUpsertWithWhereUniqueWithoutFamilyInput | Prisma.UserUpsertWithWhereUniqueWithoutFamilyInput[]
  createMany?: Prisma.UserCreateManyFamilyInputEnvelope
  set?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  disconnect?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  delete?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  connect?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  update?: Prisma.UserUpdateWithWhereUniqueWithoutFamilyInput | Prisma.UserUpdateWithWhereUniqueWithoutFamilyInput[]
  updateMany?: Prisma.UserUpdateManyWithWhereWithoutFamilyInput | Prisma.UserUpdateManyWithWhereWithoutFamilyInput[]
  deleteMany?: Prisma.UserScalarWhereInput | Prisma.UserScalarWhereInput[]
}

export type UserUncheckedUpdateManyWithoutFamilyNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutFamilyInput, Prisma.UserUncheckedCreateWithoutFamilyInput> | Prisma.UserCreateWithoutFamilyInput[] | Prisma.UserUncheckedCreateWithoutFamilyInput[]
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutFamilyInput | Prisma.UserCreateOrConnectWithoutFamilyInput[]
  upsert?: Prisma.UserUpsertWithWhereUniqueWithoutFamilyInput | Prisma.UserUpsertWithWhereUniqueWithoutFamilyInput[]
  createMany?: Prisma.UserCreateManyFamilyInputEnvelope
  set?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  disconnect?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  delete?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  connect?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  update?: Prisma.UserUpdateWithWhereUniqueWithoutFamilyInput | Prisma.UserUpdateWithWhereUniqueWithoutFamilyInput[]
  updateMany?: Prisma.UserUpdateManyWithWhereWithoutFamilyInput | Prisma.UserUpdateManyWithWhereWithoutFamilyInput[]
  deleteMany?: Prisma.UserScalarWhereInput | Prisma.UserScalarWhereInput[]
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type EnumRoleFieldUpdateOperationsInput = {
  set?: $Enums.Role
}

export type UserCreateNestedOneWithoutMood_logsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutMood_logsInput, Prisma.UserUncheckedCreateWithoutMood_logsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutMood_logsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutMood_logsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutMood_logsInput, Prisma.UserUncheckedCreateWithoutMood_logsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutMood_logsInput
  upsert?: Prisma.UserUpsertWithoutMood_logsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutMood_logsInput, Prisma.UserUpdateWithoutMood_logsInput>, Prisma.UserUncheckedUpdateWithoutMood_logsInput>
}

export type UserCreateNestedOneWithoutCalendar_eventsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCalendar_eventsInput, Prisma.UserUncheckedCreateWithoutCalendar_eventsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCalendar_eventsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutCalendar_eventsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCalendar_eventsInput, Prisma.UserUncheckedCreateWithoutCalendar_eventsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCalendar_eventsInput
  upsert?: Prisma.UserUpsertWithoutCalendar_eventsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutCalendar_eventsInput, Prisma.UserUpdateWithoutCalendar_eventsInput>, Prisma.UserUncheckedUpdateWithoutCalendar_eventsInput>
}

export type UserCreateNestedOneWithoutDaily_remindersInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutDaily_remindersInput, Prisma.UserUncheckedCreateWithoutDaily_remindersInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutDaily_remindersInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutDaily_remindersNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutDaily_remindersInput, Prisma.UserUncheckedCreateWithoutDaily_remindersInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutDaily_remindersInput
  upsert?: Prisma.UserUpsertWithoutDaily_remindersInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutDaily_remindersInput, Prisma.UserUpdateWithoutDaily_remindersInput>, Prisma.UserUncheckedUpdateWithoutDaily_remindersInput>
}

export type UserCreateWithoutFamilyInput = {
  id?: string
  email?: string | null
  password_hash: string
  alias: string
  role?: $Enums.Role
  avatar_icon: string
  timezone?: string
  mood_logs?: Prisma.MoodLogCreateNestedManyWithoutUserInput
  calendar_events?: Prisma.CalendarEventCreateNestedManyWithoutUserInput
  daily_reminders?: Prisma.DailyReminderCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutFamilyInput = {
  id?: string
  email?: string | null
  password_hash: string
  alias: string
  role?: $Enums.Role
  avatar_icon: string
  timezone?: string
  mood_logs?: Prisma.MoodLogUncheckedCreateNestedManyWithoutUserInput
  calendar_events?: Prisma.CalendarEventUncheckedCreateNestedManyWithoutUserInput
  daily_reminders?: Prisma.DailyReminderUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutFamilyInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutFamilyInput, Prisma.UserUncheckedCreateWithoutFamilyInput>
}

export type UserCreateManyFamilyInputEnvelope = {
  data: Prisma.UserCreateManyFamilyInput | Prisma.UserCreateManyFamilyInput[]
  skipDuplicates?: boolean
}

export type UserUpsertWithWhereUniqueWithoutFamilyInput = {
  where: Prisma.UserWhereUniqueInput
  update: Prisma.XOR<Prisma.UserUpdateWithoutFamilyInput, Prisma.UserUncheckedUpdateWithoutFamilyInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutFamilyInput, Prisma.UserUncheckedCreateWithoutFamilyInput>
}

export type UserUpdateWithWhereUniqueWithoutFamilyInput = {
  where: Prisma.UserWhereUniqueInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutFamilyInput, Prisma.UserUncheckedUpdateWithoutFamilyInput>
}

export type UserUpdateManyWithWhereWithoutFamilyInput = {
  where: Prisma.UserScalarWhereInput
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyWithoutFamilyInput>
}

export type UserScalarWhereInput = {
  AND?: Prisma.UserScalarWhereInput | Prisma.UserScalarWhereInput[]
  OR?: Prisma.UserScalarWhereInput[]
  NOT?: Prisma.UserScalarWhereInput | Prisma.UserScalarWhereInput[]
  id?: Prisma.UuidFilter<"User"> | string
  family_id?: Prisma.UuidFilter<"User"> | string
  email?: Prisma.StringNullableFilter<"User"> | string | null
  password_hash?: Prisma.StringFilter<"User"> | string
  alias?: Prisma.StringFilter<"User"> | string
  role?: Prisma.EnumRoleFilter<"User"> | $Enums.Role
  avatar_icon?: Prisma.StringFilter<"User"> | string
  timezone?: Prisma.StringFilter<"User"> | string
}

export type UserCreateWithoutMood_logsInput = {
  id?: string
  email?: string | null
  password_hash: string
  alias: string
  role?: $Enums.Role
  avatar_icon: string
  timezone?: string
  family: Prisma.FamilyCreateNestedOneWithoutUsersInput
  calendar_events?: Prisma.CalendarEventCreateNestedManyWithoutUserInput
  daily_reminders?: Prisma.DailyReminderCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutMood_logsInput = {
  id?: string
  family_id: string
  email?: string | null
  password_hash: string
  alias: string
  role?: $Enums.Role
  avatar_icon: string
  timezone?: string
  calendar_events?: Prisma.CalendarEventUncheckedCreateNestedManyWithoutUserInput
  daily_reminders?: Prisma.DailyReminderUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutMood_logsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutMood_logsInput, Prisma.UserUncheckedCreateWithoutMood_logsInput>
}

export type UserUpsertWithoutMood_logsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutMood_logsInput, Prisma.UserUncheckedUpdateWithoutMood_logsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutMood_logsInput, Prisma.UserUncheckedCreateWithoutMood_logsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutMood_logsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutMood_logsInput, Prisma.UserUncheckedUpdateWithoutMood_logsInput>
}

export type UserUpdateWithoutMood_logsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  alias?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  avatar_icon?: Prisma.StringFieldUpdateOperationsInput | string
  timezone?: Prisma.StringFieldUpdateOperationsInput | string
  family?: Prisma.FamilyUpdateOneRequiredWithoutUsersNestedInput
  calendar_events?: Prisma.CalendarEventUpdateManyWithoutUserNestedInput
  daily_reminders?: Prisma.DailyReminderUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutMood_logsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  family_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  alias?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  avatar_icon?: Prisma.StringFieldUpdateOperationsInput | string
  timezone?: Prisma.StringFieldUpdateOperationsInput | string
  calendar_events?: Prisma.CalendarEventUncheckedUpdateManyWithoutUserNestedInput
  daily_reminders?: Prisma.DailyReminderUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutCalendar_eventsInput = {
  id?: string
  email?: string | null
  password_hash: string
  alias: string
  role?: $Enums.Role
  avatar_icon: string
  timezone?: string
  family: Prisma.FamilyCreateNestedOneWithoutUsersInput
  mood_logs?: Prisma.MoodLogCreateNestedManyWithoutUserInput
  daily_reminders?: Prisma.DailyReminderCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutCalendar_eventsInput = {
  id?: string
  family_id: string
  email?: string | null
  password_hash: string
  alias: string
  role?: $Enums.Role
  avatar_icon: string
  timezone?: string
  mood_logs?: Prisma.MoodLogUncheckedCreateNestedManyWithoutUserInput
  daily_reminders?: Prisma.DailyReminderUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutCalendar_eventsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutCalendar_eventsInput, Prisma.UserUncheckedCreateWithoutCalendar_eventsInput>
}

export type UserUpsertWithoutCalendar_eventsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutCalendar_eventsInput, Prisma.UserUncheckedUpdateWithoutCalendar_eventsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutCalendar_eventsInput, Prisma.UserUncheckedCreateWithoutCalendar_eventsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutCalendar_eventsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutCalendar_eventsInput, Prisma.UserUncheckedUpdateWithoutCalendar_eventsInput>
}

export type UserUpdateWithoutCalendar_eventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  alias?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  avatar_icon?: Prisma.StringFieldUpdateOperationsInput | string
  timezone?: Prisma.StringFieldUpdateOperationsInput | string
  family?: Prisma.FamilyUpdateOneRequiredWithoutUsersNestedInput
  mood_logs?: Prisma.MoodLogUpdateManyWithoutUserNestedInput
  daily_reminders?: Prisma.DailyReminderUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutCalendar_eventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  family_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  alias?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  avatar_icon?: Prisma.StringFieldUpdateOperationsInput | string
  timezone?: Prisma.StringFieldUpdateOperationsInput | string
  mood_logs?: Prisma.MoodLogUncheckedUpdateManyWithoutUserNestedInput
  daily_reminders?: Prisma.DailyReminderUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutDaily_remindersInput = {
  id?: string
  email?: string | null
  password_hash: string
  alias: string
  role?: $Enums.Role
  avatar_icon: string
  timezone?: string
  family: Prisma.FamilyCreateNestedOneWithoutUsersInput
  mood_logs?: Prisma.MoodLogCreateNestedManyWithoutUserInput
  calendar_events?: Prisma.CalendarEventCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutDaily_remindersInput = {
  id?: string
  family_id: string
  email?: string | null
  password_hash: string
  alias: string
  role?: $Enums.Role
  avatar_icon: string
  timezone?: string
  mood_logs?: Prisma.MoodLogUncheckedCreateNestedManyWithoutUserInput
  calendar_events?: Prisma.CalendarEventUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutDaily_remindersInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutDaily_remindersInput, Prisma.UserUncheckedCreateWithoutDaily_remindersInput>
}

export type UserUpsertWithoutDaily_remindersInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutDaily_remindersInput, Prisma.UserUncheckedUpdateWithoutDaily_remindersInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutDaily_remindersInput, Prisma.UserUncheckedCreateWithoutDaily_remindersInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutDaily_remindersInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutDaily_remindersInput, Prisma.UserUncheckedUpdateWithoutDaily_remindersInput>
}

export type UserUpdateWithoutDaily_remindersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  alias?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  avatar_icon?: Prisma.StringFieldUpdateOperationsInput | string
  timezone?: Prisma.StringFieldUpdateOperationsInput | string
  family?: Prisma.FamilyUpdateOneRequiredWithoutUsersNestedInput
  mood_logs?: Prisma.MoodLogUpdateManyWithoutUserNestedInput
  calendar_events?: Prisma.CalendarEventUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutDaily_remindersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  family_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  alias?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  avatar_icon?: Prisma.StringFieldUpdateOperationsInput | string
  timezone?: Prisma.StringFieldUpdateOperationsInput | string
  mood_logs?: Prisma.MoodLogUncheckedUpdateManyWithoutUserNestedInput
  calendar_events?: Prisma.CalendarEventUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateManyFamilyInput = {
  id?: string
  email?: string | null
  password_hash: string
  alias: string
  role?: $Enums.Role
  avatar_icon: string
  timezone?: string
}

export type UserUpdateWithoutFamilyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  alias?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  avatar_icon?: Prisma.StringFieldUpdateOperationsInput | string
  timezone?: Prisma.StringFieldUpdateOperationsInput | string
  mood_logs?: Prisma.MoodLogUpdateManyWithoutUserNestedInput
  calendar_events?: Prisma.CalendarEventUpdateManyWithoutUserNestedInput
  daily_reminders?: Prisma.DailyReminderUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutFamilyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  alias?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  avatar_icon?: Prisma.StringFieldUpdateOperationsInput | string
  timezone?: Prisma.StringFieldUpdateOperationsInput | string
  mood_logs?: Prisma.MoodLogUncheckedUpdateManyWithoutUserNestedInput
  calendar_events?: Prisma.CalendarEventUncheckedUpdateManyWithoutUserNestedInput
  daily_reminders?: Prisma.DailyReminderUncheckedUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateManyWithoutFamilyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  alias?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  avatar_icon?: Prisma.StringFieldUpdateOperationsInput | string
  timezone?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type UserCountOutputType
 */

export type UserCountOutputType = {
  mood_logs: number
  calendar_events: number
  daily_reminders: number
}

export type UserCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mood_logs?: boolean | UserCountOutputTypeCountMood_logsArgs
  calendar_events?: boolean | UserCountOutputTypeCountCalendar_eventsArgs
  daily_reminders?: boolean | UserCountOutputTypeCountDaily_remindersArgs
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCountOutputType
   */
  select?: Prisma.UserCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountMood_logsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MoodLogWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountCalendar_eventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CalendarEventWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountDaily_remindersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DailyReminderWhereInput
}


export type UserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  family_id?: boolean
  email?: boolean
  password_hash?: boolean
  alias?: boolean
  role?: boolean
  avatar_icon?: boolean
  timezone?: boolean
  family?: boolean | Prisma.FamilyDefaultArgs<ExtArgs>
  mood_logs?: boolean | Prisma.User$mood_logsArgs<ExtArgs>
  calendar_events?: boolean | Prisma.User$calendar_eventsArgs<ExtArgs>
  daily_reminders?: boolean | Prisma.User$daily_remindersArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user"]>

export type UserSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  family_id?: boolean
  email?: boolean
  password_hash?: boolean
  alias?: boolean
  role?: boolean
  avatar_icon?: boolean
  timezone?: boolean
  family?: boolean | Prisma.FamilyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user"]>

export type UserSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  family_id?: boolean
  email?: boolean
  password_hash?: boolean
  alias?: boolean
  role?: boolean
  avatar_icon?: boolean
  timezone?: boolean
  family?: boolean | Prisma.FamilyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user"]>

export type UserSelectScalar = {
  id?: boolean
  family_id?: boolean
  email?: boolean
  password_hash?: boolean
  alias?: boolean
  role?: boolean
  avatar_icon?: boolean
  timezone?: boolean
}

export type UserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "family_id" | "email" | "password_hash" | "alias" | "role" | "avatar_icon" | "timezone", ExtArgs["result"]["user"]>
export type UserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  family?: boolean | Prisma.FamilyDefaultArgs<ExtArgs>
  mood_logs?: boolean | Prisma.User$mood_logsArgs<ExtArgs>
  calendar_events?: boolean | Prisma.User$calendar_eventsArgs<ExtArgs>
  daily_reminders?: boolean | Prisma.User$daily_remindersArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}
export type UserIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  family?: boolean | Prisma.FamilyDefaultArgs<ExtArgs>
}
export type UserIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  family?: boolean | Prisma.FamilyDefaultArgs<ExtArgs>
}

export type $UserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "User"
  objects: {
    family: Prisma.$FamilyPayload<ExtArgs>
    mood_logs: Prisma.$MoodLogPayload<ExtArgs>[]
    calendar_events: Prisma.$CalendarEventPayload<ExtArgs>[]
    daily_reminders: Prisma.$DailyReminderPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    family_id: string
    email: string | null
    password_hash: string
    alias: string
    role: $Enums.Role
    avatar_icon: string
    timezone: string
  }, ExtArgs["result"]["user"]>
  composites: {}
}

export type UserGetPayload<S extends boolean | null | undefined | UserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserPayload, S>

export type UserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserCountAggregateInputType | true
  }

export interface UserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['User'], meta: { name: 'User' } }
  /**
   * Find zero or one User that matches the filter.
   * @param {UserFindUniqueArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserFindUniqueArgs>(args: Prisma.SelectSubset<T, UserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one User that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserFindUniqueOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserFindFirstArgs>(args?: Prisma.SelectSubset<T, UserFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Users
   * const users = await prisma.user.findMany()
   * 
   * // Get first 10 Users
   * const users = await prisma.user.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userWithIdOnly = await prisma.user.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserFindManyArgs>(args?: Prisma.SelectSubset<T, UserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a User.
   * @param {UserCreateArgs} args - Arguments to create a User.
   * @example
   * // Create one User
   * const User = await prisma.user.create({
   *   data: {
   *     // ... data to create a User
   *   }
   * })
   * 
   */
  create<T extends UserCreateArgs>(args: Prisma.SelectSubset<T, UserCreateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Users.
   * @param {UserCreateManyArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserCreateManyArgs>(args?: Prisma.SelectSubset<T, UserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Users and returns the data saved in the database.
   * @param {UserCreateManyAndReturnArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Users and only return the `id`
   * const userWithIdOnly = await prisma.user.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a User.
   * @param {UserDeleteArgs} args - Arguments to delete one User.
   * @example
   * // Delete one User
   * const User = await prisma.user.delete({
   *   where: {
   *     // ... filter to delete one User
   *   }
   * })
   * 
   */
  delete<T extends UserDeleteArgs>(args: Prisma.SelectSubset<T, UserDeleteArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one User.
   * @param {UserUpdateArgs} args - Arguments to update one User.
   * @example
   * // Update one User
   * const user = await prisma.user.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserUpdateArgs>(args: Prisma.SelectSubset<T, UserUpdateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Users.
   * @param {UserDeleteManyArgs} args - Arguments to filter Users to delete.
   * @example
   * // Delete a few Users
   * const { count } = await prisma.user.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserUpdateManyArgs>(args: Prisma.SelectSubset<T, UserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users and returns the data updated in the database.
   * @param {UserUpdateManyAndReturnArgs} args - Arguments to update many Users.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Users and only return the `id`
   * const userWithIdOnly = await prisma.user.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one User.
   * @param {UserUpsertArgs} args - Arguments to update or create a User.
   * @example
   * // Update or create a User
   * const user = await prisma.user.upsert({
   *   create: {
   *     // ... data to create a User
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the User we want to update
   *   }
   * })
   */
  upsert<T extends UserUpsertArgs>(args: Prisma.SelectSubset<T, UserUpsertArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCountArgs} args - Arguments to filter Users to count.
   * @example
   * // Count the number of Users
   * const count = await prisma.user.count({
   *   where: {
   *     // ... the filter for the Users we want to count
   *   }
   * })
  **/
  count<T extends UserCountArgs>(
    args?: Prisma.Subset<T, UserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserAggregateArgs>(args: Prisma.Subset<T, UserAggregateArgs>): Prisma.PrismaPromise<GetUserAggregateType<T>>

  /**
   * Group by User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserGroupByArgs['orderBy'] }
      : { orderBy?: UserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the User model
 */
readonly fields: UserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for User.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  family<T extends Prisma.FamilyDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FamilyDefaultArgs<ExtArgs>>): Prisma.Prisma__FamilyClient<runtime.Types.Result.GetResult<Prisma.$FamilyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  mood_logs<T extends Prisma.User$mood_logsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$mood_logsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MoodLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  calendar_events<T extends Prisma.User$calendar_eventsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$calendar_eventsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CalendarEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  daily_reminders<T extends Prisma.User$daily_remindersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$daily_remindersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DailyReminderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the User model
 */
export interface UserFieldRefs {
  readonly id: Prisma.FieldRef<"User", 'String'>
  readonly family_id: Prisma.FieldRef<"User", 'String'>
  readonly email: Prisma.FieldRef<"User", 'String'>
  readonly password_hash: Prisma.FieldRef<"User", 'String'>
  readonly alias: Prisma.FieldRef<"User", 'String'>
  readonly role: Prisma.FieldRef<"User", 'Role'>
  readonly avatar_icon: Prisma.FieldRef<"User", 'String'>
  readonly timezone: Prisma.FieldRef<"User", 'String'>
}
    

// Custom InputTypes
/**
 * User findUnique
 */
export type UserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findUniqueOrThrow
 */
export type UserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findFirst
 */
export type UserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findFirstOrThrow
 */
export type UserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findMany
 */
export type UserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User create
 */
export type UserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to create a User.
   */
  data: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
}

/**
 * User createMany
 */
export type UserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * User createManyAndReturn
 */
export type UserCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * User update
 */
export type UserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to update a User.
   */
  data: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
  /**
   * Choose, which User to update.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User updateMany
 */
export type UserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User updateManyAndReturn
 */
export type UserUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * User upsert
 */
export type UserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The filter to search for the User to update in case it exists.
   */
  where: Prisma.UserWhereUniqueInput
  /**
   * In case the User found by the `where` argument doesn't exist, create a new User with this data.
   */
  create: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
  /**
   * In case the User was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
}

/**
 * User delete
 */
export type UserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter which User to delete.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User deleteMany
 */
export type UserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Users to delete
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to delete.
   */
  limit?: number
}

/**
 * User.mood_logs
 */
export type User$mood_logsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MoodLog
   */
  select?: Prisma.MoodLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MoodLog
   */
  omit?: Prisma.MoodLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MoodLogInclude<ExtArgs> | null
  where?: Prisma.MoodLogWhereInput
  orderBy?: Prisma.MoodLogOrderByWithRelationInput | Prisma.MoodLogOrderByWithRelationInput[]
  cursor?: Prisma.MoodLogWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MoodLogScalarFieldEnum | Prisma.MoodLogScalarFieldEnum[]
}

/**
 * User.calendar_events
 */
export type User$calendar_eventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarEvent
   */
  select?: Prisma.CalendarEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarEvent
   */
  omit?: Prisma.CalendarEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalendarEventInclude<ExtArgs> | null
  where?: Prisma.CalendarEventWhereInput
  orderBy?: Prisma.CalendarEventOrderByWithRelationInput | Prisma.CalendarEventOrderByWithRelationInput[]
  cursor?: Prisma.CalendarEventWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CalendarEventScalarFieldEnum | Prisma.CalendarEventScalarFieldEnum[]
}

/**
 * User.daily_reminders
 */
export type User$daily_remindersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DailyReminder
   */
  select?: Prisma.DailyReminderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DailyReminder
   */
  omit?: Prisma.DailyReminderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DailyReminderInclude<ExtArgs> | null
  where?: Prisma.DailyReminderWhereInput
  orderBy?: Prisma.DailyReminderOrderByWithRelationInput | Prisma.DailyReminderOrderByWithRelationInput[]
  cursor?: Prisma.DailyReminderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DailyReminderScalarFieldEnum | Prisma.DailyReminderScalarFieldEnum[]
}

/**
 * User without action
 */
export type UserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
}
